from django.conf import settings

ASR_MODEL_NAME = settings.ASR_MODEL_NAME
SUMMARIZER_MODEL_NAME = settings.SUMMARIZER_MODEL_NAME
DATE_ORDER = settings.DATE_ORDER

SUMMARIZER_MAX_LEN = settings.SUMMARIZER_MAX_LEN
SUMMARIZER_MIN_LEN = settings.SUMMARIZER_MIN_LEN
CHUNK_MAX_CHARS = settings.CHUNK_MAX_CHARS
TOKENIZER_MODEL_MAX_LENGTH = settings.TOKENIZER_MODEL_MAX_LENGTH

MAX_TEXT_LENGTH = settings.MAX_TEXT_LENGTH

HF_API_KEY = settings.HF_API_KEY
